sudo: false
language: rust
rust: stable

os:
  - linux
  - osx

cache:
  apt: true
  directories:
    - target/debug/deps
    - target/debug/build

before_script: |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

after_success: |
  travis-cargo coveralls

