[package]
name = "chaos"
version = "0.1.0"
authors = ["vegai"]

[dependencies]
rust-crypto = "0.2"
rustc-serialize = "*"
serde = "*"
serde_json = "*"
serde_macros = "*"
dotenv = "*"
rand = "*"
shellexpand = "*"
