[package]
name = "chaos"
version = "0.1.0"
description = "Password metadata storage and xsalsa20 hasher"
license = "Unlicense"
authors = ["vegai@iki.fi"]

[dependencies]
rust-crypto = "0.2"
rustc-serialize = "0.3"
serde = "0.7"
serde_json = "0.7"
serde_macros = "0.7"
rand = "0.3"
shellexpand = "0.1"
clap = "2.3"
